start = (
	'*WELCOME TO HEALTH ALERT*\n\n'
	'Get information and guidance about COVID-19 and related health '
	'topics.\n\n'
	'Reply with a number, emoji or *WORD IN BOLD* to explore one of these '
	'topics:\n\n'
	'*1* 🔢 *LATEST* _news & cases_\n'
	'*2* 💉 *VACCINE* _updates_\n'
	'*3* 🌞 *HEALTH* _topics_\n'
	'*4* 🦠 *COVID-19* _info and advice_\n'
	'*5* 🔗 *CONNECT* _and share_\n'
	'*6* 🌐 *LANGUAGE* _choice_\n'
	'*7* 📄 *TERMS* _and privacy_\n'
	'*8* 🔔 *ALERT* _settings_'
)
reply_1_latest = (
	'[📚] *Topic of the day:*\n'
	'*Vaccines, variants and herd immunity*\n\n'
	'As new variants emerge people are wondering if they should wait to '
	'get vaccinated? Get answers about COVID-19 vaccines and variants with '
	'WHO\'s Dr Soumya Swaminathan.\n\n'
	'📹 Watch at https://youtu.be/DV2JF2jfpiY\n\n'
	'🩹 _Or reply *2* for more on *VACCINES*_'
)
reply_2_vaccine = (
	'*VACCINES* 🩹\n\n'
	'COVID-19 vaccines are safe and effective.\n\n'
	'Reply with a number below to find out:\n\n'
	'*21* How vaccines work\n'
	'*22* Vaccine testing\n'
	'*23* Vaccine safety\n'
	'*24* How long protection lasts\n'
	'*25* Access to vaccines\n'
	'*26* Stopping the pandemic\n'
	'*27* About vaccine options\n'
	'- 271 Moderna\n'
	'- 272 Oxford/AstraZeneca\n'
	'- 273 Pfizer/BioNTech\n'
	'- 274 Johnson & Johnson\n\n'
	'*Watch or Listen 👇 to Science in 5:*\n\n'
	'#16 How vaccines work?\n'
	'📹 youtu.be/V4JAo9PhnoI\n\n'
	'#23 I am vaccinated, what next\n'
	'📹 youtu.be/YgfeV9b1K4M\n\n'
	'#30 Vaccines: When and why?\n'
	'📹 youtu.be/Fy3tcSdH-2o\n\n'
	'-----\n'
	'Reply:\n'
	'❓ *43* for *QUESTIONS* & answers\n'
	'🔔 *8* to sign up for WHO *ALERTS*\n'
	'📌 *0* for the *MENU*'
)
reply_21 = (
	'*HOW DO VACCINES WORK?*\n\n'
	'Vaccines are a simple, safe and effective way to protect people '
	'against harmful diseases.\n\n'
	'A vaccine uses your body\'s natural defenses to build resistance to '
	'an infection.\n\n'
	'The vaccine trains your immune system to create antibodies, just as '
	'it does when it\'s exposed to a disease.\n\n'
	'Vaccines contain killed or weakened forms of viruses or bacteria. '
	'They do not give you the disease. They do not put you at risk of '
	'serious symptoms.\n\n'
	'Most vaccines are given by injection, but some are given orally (by '
	'mouth) or sprayed into the nose.\n\n'
	'WHO estimates that vaccines save between 2 and 3 million lives every '
	'year.\n\n'
	'📹 *Watch Science in 5*\n'
	'#16 How vaccines work\n'
	'https://youtu.be/V4JAo9PhnoI\n\n'
	'⏩ Share accurate vaccine information with your loved ones. Send this '
	'link: wa.me/41798931892?text=vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_22 = (
	'*HOW ARE VACCINES DEVELOPED AND TESTED?*\n\n'
	'Every vaccine must go through large-scale and strict testing to make '
	'sure it is safe and that it works.\n\n'
	'*Testing*\n'
	'A new vaccine is first tested in animals to check that it is safe '
	'and to show that it can prevent the disease.\n\n'
	'Then scientists do 3 phases of human clinical trials:\n\n'
	'In phase I, a small number of volunteers get the vaccine. The vaccine '
	'is tested for safety and to make sure it kicks off an immune '
	'response. Researchers also work out the right dosage.\n\n'
	'In phase II, the vaccine is usually given to hundreds of volunteers. '
	'It is checked for side effects and to make sure it creates an immune '
	'response.\n\n'
	'Phase III trials involve thousands of volunteers. Some get the '
	'vaccine and some do not. Researchers compare the results to see if '
	'the vaccine is safe and effective.\n\n'
	'*Approval*\n'
	'The clinical trials results are reviewed to make sure that the '
	'vaccine works and is safe. The manufacturing process is also '
	'reviewed. These checks are needed for vaccine approval so that it can '
	'be added to a national immunization programme.\n\n'
	'*Monitoring*\n'
	'The vaccine rollout is closely monitored. This helps pick up any '
	'unexpected negative effects and further checks its effectiveness.\n\n'
	'📹 *Watch Science in 5*\n'
	'#17 Vaccine approvals\n'
	'https://youtu.be/ofnMToabi50\n\n'
	'⏩ *Share* accurate vaccine information with your loved ones. Send '
	'this link: wa.me/41798931892?text=vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_23 = (
	'*ARE VACCINES SAFE?*\n\n'
	'Vaccines are very safe. A person is far more likely to be seriously '
	'harmed by a disease than by a vaccine.\n\n'
	'Common vaccines (like the Polio vaccine) have been used for decades. '
	'Millions of people receive them safely every year.\n\n'
	'Every vaccine needs to go through large-scale testing before it can '
	'be used. Vaccines are then monitored.\n\n'
	'Side effects can occur after getting a vaccine. However, these '
	'are usually minor and don\'t last long, such as a sore arm or a mild '
	'fever. More serious side effects are possible but are extremely '
	'rare.\n\n'
	'📹 *Watch Science in 5*\n'
	'#24 Vaccine myths vs science\n'
	'https://youtu.be/B-aaVh0BQSw\n\n'
	'⏩ *Share* accurate vaccine information with your loved ones. Send '
	'this link: wa.me/41798931892?text=vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_24 = (
	'*HOW LONG DOES PROTECTION LAST?*\n\n'
	'It\'s too early to know if COVID-19 vaccines will provide long-term '
	'protection. More research is needed.\n\n'
	'People who have had COVID-19 seem to develop an immune response that '
	'protects them from being infected again. We are still learning how '
	'strong this protection is, and how long it lasts.\n\n'
	'It\'s also not yet clear how many doses of a COVID-19 vaccine will '
	'be needed. Most COVID-19 vaccines being tested now are using two '
	'doses a few weeks apart.\n\n'
	'📹 *Watch Science in 5*\n'
	'#23 I am vaccinated, what next?\n'
	'https://youtu.be/YgfeV9b1K4M\n\n'
	'⏩ *Share* accurate vaccine information with your loved ones. Send '
	'this link: wa.me/41798931892?text=vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_25 = (
	'*WHO SHOULD GET VACCINES FIRST?*\n\n'
	'WHO believes that everyone across the world should have access to '
	'safe and effective COVID-19 vaccines. Vaccination should start with '
	'those at highest risk.\n\n'
	'👩‍⚕️ *Priority groups*\n'
	'The decision about who should get vaccinated first should be based '
	'on:\n'
	'- how the virus is spreading in each country, and\n'
	'- how many doses of vaccine are available.\n\n'
	'Where infection is spreading widely and there are limited vaccine '
	'doses, these groups should be vaccinated first:\n'
	'- high-risk health workers\n'
	'- older, at-risk adults\n'
	'- other older adults\n'
	'- people with co-morbidities\n'
	'- other at-risk groups\n'
	'- school staff\n'
	'- other essential workers\n\n'
	'🌍 *Global access*\n'
	'WHO is working to make sure that all countries get a fair share of '
	'COVID-19 vaccines and treatments.\n\n'
	'Each country should receive doses of safe and effective vaccines in '
	'proportion to their population. These should be used to vaccinate the '
	'highest-priority groups.\n\n'
	'When more vaccine doses are available, these should be distributed to '
	'all countries to vaccinate other priority groups.\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_26 = (
	'*HOW QUICKLY CAN VACCINES STOP THE PANDEMIC?*\n\n'
	'Safe and effective vaccines will be a gamechange but we don\'t yet '
	'know how long it will take to stop the pandemic.\n\n'
	'How quickly vaccines can stop the pandemic will depend on:\n'
	'- how well it works\n'
	'- when vaccines are approved\n'
	'- how quickly doses can be produced\n'
	'- how quickly they are distributed\n'
	'- how many people get vaccinated\n\n'
	'Most scientists expect that COVID-19 vaccines will not be 100% '
	'effective. More research is needed to know how effective vaccines are '
	'against different variants.\n\n'
	'A vaccine will help protect you against disease if you get the virus. '
	'We do not know yet if it will also stop the virus from spreading to '
	'other people.\n\n'
	'Vaccines are a critical tool but we must continue to;\n'
	'- wear masks\n'
	'- physically distance\n'
	'- avoid crowded places\n\n'
	'We need as many people as possible to get vaccinated to help stop the '
	'pandemic. When it\'s your turn, get the vaccine.\n\n'
	'📹 *Watch Science in 5*\n'
	'#20 Variants & vaccines\n'
	'https://youtu.be/gjnPZKMNmqc\n\n'
	'⏩ *Share* accurate vaccine information with your loved ones. Send '
	'this link: wa.me/41798931892?text=vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
reply_27 = (
	'*ABOUT VACCINE OPTIONS*\n\n'
	'*271* Moderna vaccine\n'
	'*272* Oxford/AstraZeneca vaccine\n'
	'*273* Pfizer-BioNTech vaccine\n'
	'*274* Johnson & Johnson vaccine\n\n'
	'-----\n'
	'Reply:\n'
	'💉 *2* for *VACCINE* updates\n'
	'📌 *0* for the main *MENU*\n'
	'🔔 *8* to sign up for WHO *ALERTS*'
)
